// Read-time resolver that keeps storefront imagery local.
//
// A mirrored third-party URL (see aliases.mjs, generated by
// scripts/mirror-catalog-images.js) maps to its local file. Anything still
// remote and unmirrored falls back to a bundled placeholder, so a storefront
// card never fires a request at a third-party CDN. First-party hosts and
// already-local values (data:, blob:, relative paths) pass through untouched.
//
// Kept as its own ESM module — rather than living in product-data.js (CommonJS
// package, so Node refuses to import it) — so scripts/localize-catalog-image.test.js
// can exercise it directly.
import { REMOTE_IMAGE_ALIASES } from './aliases.mjs';

export const CATALOG_IMAGE_PLACEHOLDER = 'products/catalog/image-unavailable.svg';

// Hosts we serve ourselves. Their images are not a third-party dependency, so
// they are left untouched rather than replaced with the placeholder.
export const FIRST_PARTY_IMAGE_HOSTS = [
    'backdoorco.xyz',
    'backdoorco2.netlify.app',
    'backdoorco.vercel.app',
    'localhost',
    '127.0.0.1',
];

function isFirstPartyImageUrl(value) {
    try {
        const host = new URL(value).host.toLowerCase();
        return FIRST_PARTY_IMAGE_HOSTS.some((own) => host === own || host.endsWith(`.${own}`));
    } catch {
        return false;
    }
}

export function localizeCatalogImage(value) {
    const raw = String(value || '').trim();
    if (!raw) return raw;
    if (REMOTE_IMAGE_ALIASES[raw]) return REMOTE_IMAGE_ALIASES[raw];
    const bare = raw.split('?')[0].split('#')[0];
    if (bare !== raw && REMOTE_IMAGE_ALIASES[bare]) return REMOTE_IMAGE_ALIASES[bare];
    // data:, blob: and relative paths are already local (or generated in-page).
    if (!/^https?:\/\//i.test(raw)) return raw;
    if (isFirstPartyImageUrl(raw)) return raw;
    return CATALOG_IMAGE_PLACEHOLDER;
}
