[build]
  publish = "."
  ignore = "git diff --quiet \"$CACHED_COMMIT_REF\" \"$COMMIT_REF\" -- . ':(exclude).github/**' ':(exclude)diff.txt' ':(exclude)deploy.ps1' ':(exclude)check-homepage.js' ':(exclude)check-shop-page.js' ':(exclude)test-browser.js' ':(exclude)server.js'"

[functions]
  directory = "netlify/functions"
